"""PRD section order and key constants."""

SECTION_ORDER: list[tuple[str, str]] = [
    ("executive_summary", "Executive Summary"),
    ("executive_product_summary", "Executive Product Summary"),
    ("engineering_plan", "Engineering Plan"),
    ("problem_statement", "Problem Statement"),
    ("user_personas", "User Personas"),
    ("functional_requirements", "Functional Requirements"),
    ("no_functional_requirements", "Non-Functional Requirements"),
    ("edge_cases", "Edge Cases"),
    ("error_handling", "Error Handling"),
    ("success_metrics", "Success Metrics"),
    ("dependencies", "Dependencies"),
    ("assumptions", "Assumptions"),
]

SECTION_KEYS: list[str] = [key for key, _ in SECTION_ORDER]

# Sections generated by specialist agents (CEO, Eng Manager) after the
# executive summary and before the main section-by-section loop.
# These are NOT part of the normal draft→critique→refine cycle.
SPECIALIST_SECTION_KEYS: set[str] = {
    "executive_product_summary",
    "engineering_plan",
}
